"""Approval API endpoints for the human approval workflow.

These endpoints are designed to be called from the frontend dashboard
or any HTTP client. They follow the same handler pattern as the existing
API (Lambda/API Gateway compatible).

Security design:
- The approval_id is a opaque token generated by the backend.
- Approving/rejecting flows through the PolicyEngine, not the UI.
- A modified client cannot bypass the security boundary.
"""

import json
from typing import Any

from sentinel.integrations.strands_agent import SentinelStrandsAgent
from sentinel.tools.fixtures import FixtureStore

# Module-level state for the demo. In production this would be DynamoDB.
_agent: SentinelStrandsAgent | None = None


def _get_agent() -> SentinelStrandsAgent:
    """Lazy-init a singleton agent for the approval demo."""
    global _agent
    if _agent is None:
        _agent = SentinelStrandsAgent(store=FixtureStore(poisoned=False), vulnerable=False)
        _agent.run(
            "Find the lowest-cost laptop supplier, compare prices, "
            "and prepare a purchase order for 10 units."
        )
    return _agent


def reset_agent() -> None:
    """Reset the demo agent (for fresh demo runs)."""
    global _agent
    _agent = None


def get_pending_approvals() -> dict[str, Any]:
    """Return all pending ESCALATE decisions."""
    agent = _get_agent()
    return {
        "pending": agent.pending_approvals(),
        "security_events": agent.security_events(),
    }


def approve_action(approval_id: str, operator: str = "human") -> dict[str, Any]:
    """Approve a pending escalation. Executes the tool through the security boundary."""
    agent = _get_agent()
    result = agent.approve(approval_id, operator)
    if result is None:
        return {"error": "Approval not found or already decided", "approval_id": approval_id}
    return {
        "approval_id": approval_id,
        "status": "approved",
        "result": result,
        "security_events": agent.security_events(),
    }


def reject_action(approval_id: str, operator: str = "human") -> dict[str, Any]:
    """Reject a pending escalation."""
    agent = _get_agent()
    success = agent.reject(approval_id, operator)
    if not success:
        return {"error": "Approval not found or already decided", "approval_id": approval_id}
    return {
        "approval_id": approval_id,
        "status": "rejected",
        "security_events": agent.security_events(),
    }


def approval_handler(event: dict[str, Any], context: Any = None) -> dict[str, Any]:
    """Handle approval-related API routes."""
    method = event.get("httpMethod", "GET")
    path = event.get("path", "/")

    if method == "POST" and path == "/approvals":
        body = json.loads(event.get("body", "{}"))
        approval_id = body.get("approval_id")
        decision = body.get("decision", "APPROVE")
        operator = body.get("operator", "human")
        if not approval_id:
            return _response(400, {"error": "approval_id is required"})
        if decision == "APPROVE":
            result = approve_action(approval_id, operator)
        elif decision == "REJECT":
            result = reject_action(approval_id, operator)
        else:
            return _response(400, {"error": f"Invalid decision: {decision}"})
        return _response(200, result)

    if method == "GET" and path == "/approvals":
        return _response(200, get_pending_approvals())

    if method == "POST" and path == "/approvals/reset":
        reset_agent()
        return _response(200, {"status": "reset"})

    return _response(404, {"error": "route not found"})


def _response(status_code: int, body: dict[str, Any]) -> dict[str, Any]:
    return {
        "statusCode": status_code,
        "headers": {"content-type": "application/json"},
        "body": json.dumps(body),
    }
