"""Approval API endpoints for the human approval workflow.

These endpoints are designed to be called from the frontend dashboard
or any HTTP client. They follow the same handler pattern as the existing
API (Lambda/API Gateway compatible).

Security design:
- The approval_id is an opaque token generated by the backend.
- The backend retrieves the authoritative ApprovalRecord and performs
  the actual authorization through PolicyEngine.execute_approved().
- The client CANNOT supply tool_name, arguments, risk_score, or any
  other security-relevant field. Only approval_id and operator are accepted.
- A modified client cannot bypass the security boundary.
"""

import json
import threading
from typing import Any

from sentinel.tools.fixtures import FixtureStore

_agent: Any = None
_agent_lock = threading.Lock()


def _get_agent() -> Any:
    """Lazy-init a singleton agent for the approval demo.

    Strands SDK is imported inside the function so the Vercel serverless
    function can boot without it (approval routes degrade gracefully).
    """
    global _agent
    if _agent is not None:
        return _agent
    with _agent_lock:
        if _agent is not None:
            return _agent
        from sentinel.integrations.strands_agent import SentinelStrandsAgent
        agent = SentinelStrandsAgent(store=FixtureStore(poisoned=False), vulnerable=False)
        agent.run(
            "Find the lowest-cost laptop supplier, compare prices, "
            "and prepare a purchase order for 10 units."
        )
        _agent = agent
        return _agent


def reset_agent() -> None:
    """Reset the demo agent (for fresh demo runs)."""
    global _agent
    with _agent_lock:
        _agent = None


def get_pending_approvals() -> dict[str, Any]:
    """Return all pending ESCALATE decisions."""
    agent = _get_agent()
    return {
        "pending": agent.pending_approvals(),
        "security_events": agent.security_events(),
    }


def approve_action(approval_id: str, operator: str = "human") -> dict[str, Any]:
    """Approve a pending escalation.

    The backend retrieves the authoritative record for this approval_id
    and executes the tool through PolicyEngine.execute_approved().
    No client-supplied tool/arguments/risk fields are trusted.
    """
    agent = _get_agent()
    result = agent.approve(approval_id, operator)
    if result is None:
        return {"error": "Approval not found or already decided", "approval_id": approval_id}
    return {
        "approval_id": approval_id,
        "status": "approved",
        "result": result,
        "security_events": agent.security_events(),
    }


def reject_action(approval_id: str, operator: str = "human") -> dict[str, Any]:
    """Reject a pending escalation."""
    agent = _get_agent()
    success = agent.reject(approval_id, operator)
    if not success:
        return {"error": "Approval not found or already decided", "approval_id": approval_id}
    return {
        "approval_id": approval_id,
        "status": "rejected",
        "security_events": agent.security_events(),
    }


def approval_handler(event: dict[str, Any], context: Any = None) -> dict[str, Any]:
    """Handle approval-related API routes.

    The client supplies only approval_id and optionally decision/operator.
    All security context (tool, arguments, risk, run_id) is derived from
    the backend-stored ApprovalRecord. A malicious client cannot inject
    arbitrary tool calls through this handler.
    """
    from sentinel.api.router import json_body, normalize_path, request_method

    method = request_method(event)
    path = normalize_path(event)

    if method == "POST" and path == "/approvals":
        body = json_body(event)
        if not body and event.get("body"):
            return _response(400, {"error": "Invalid JSON body"})
        approval_id = body.get("approval_id")
        decision = body.get("decision", "APPROVE")
        operator = body.get("operator", "human")
        if not approval_id or not isinstance(approval_id, str):
            return _response(400, {"error": "approval_id is required"})
        if decision == "APPROVE":
            result = approve_action(approval_id, operator)
        elif decision == "REJECT":
            result = reject_action(approval_id, operator)
        else:
            return _response(400, {"error": f"Invalid decision: {decision}"})
        return _response(200, result)

    if method == "GET" and path == "/approvals":
        return _response(200, get_pending_approvals())

    if method == "POST" and path == "/approvals/reset":
        reset_agent()
        return _response(200, {"status": "reset"})

    return _response(404, {"error": "route not found"})


def _response(status_code: int, body: dict[str, Any]) -> dict[str, Any]:
    return {
        "statusCode": status_code,
        "headers": {"content-type": "application/json"},
        "body": json.dumps(body),
    }
